### ISSUE TITLE
Search: Exact phrase (in quotes) does not return expected results

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#640]
Is there a reason why "exact phrase" searches in quotes aren't working? This was dealt with regarding attachment search a while back (#320 ), but that issue was closed prior to the Semaphore integration ... does the integration conflict with "exact phrase" search? 

We've had some high-level requests to provide this on the site, as Metro uses a lot of generic language for specific programs. For example, "It's Off Limits" is the name of a sexual harassment prevention campaign. A search for It's Off Limits and other similarly generic names without quotes is nearly useless, and I've ended up directing users to go to metro.legistar.com in order to run a search with quotes ... which is the last place I want to have to send people for a solution!
Could you refresh my memory on why exact phrase search is no longer available?

**Comment by hancush** [comment]
Hey, @shrayshray, thanks for calling this out! I goofed up phrase search during the integration, but the integration doesn't preclude supporting it, so I started a repair over in #662. (It's currently deployed to staging if you want to play around.)

One important note: Phrases / search terms containing single quotes, e.g., "It's Off Limits", are behaving really strangely! Looks like we've run into this problem in the past in our Chicago instance: https://github.com/datamade/chi-councilmatic/issues/85

I'm going to spend some research time (i.e., [time we get at DataMade for learning](https://github.com/datamade/how-to/tree/master/investment-time), not time we bill to you all) getting a better handle on the root of this issue and hopefully identifying a solution! Will hopefully have an update for you later this week.

**Comment by shrayshray** [comment]
Right before I read this, I created #663 to address single quotes smh. Sorry, please feel free to close if you're addressing it elsewhere!

**Comment by hancush** [comment]
@shrayshray I've deployed a patch for exact phrase search and display of search terms containing single quotes (#663) to the staging site. Note that, behind the scenes, our search engine is still struggling to find results for terms containing single quotes. I've broken that off into a separate issue, #666. Besides that, would you like to play around and confirm that keyword search and phrase search are behaving as expected, and search terms containing single quotes are at least displayed correctly in the search bar?

**Comment by shrayshray** [comment]
@hancush single quotes are displayed correctly in the search bar!
It still doesn't look like single quotes are being recognized in keyword searches or phrase searches. But it might just be in the UI - single quotes are not highlighted in blue in the text under the report showing the match. Results from "It's Off Limits" do not highlight "it's", but do highlight "its" when it appears. Results for "Bus 60'Ze" highlight "Bus 60" and "Ze", but not the single quote between them.
Results for keyword search for "It's off Limits":
![image](https://user-images.githubusercontent.com/28063988/98736168-56304e80-2359-11eb-8a9d-d3c936761395.png)

Results for keyword search for "Bus 60'Ze W/ Byd-5":
![image](https://user-images.githubusercontent.com/28063988/98736888-48c79400-235a-11eb-80b9-c3ce8366175f.png)

Results for phrase search for "bus 60'Ze":
![image](https://user-images.githubusercontent.com/28063988/98736961-64329f00-235a-11eb-9b92-d301a72013e6.png)

**Comment by hancush** [comment]
Exact phrases, except when they contain apostophes, are working as expected. Will take this live, @shrayshray will drop #666 into backlog when Metro ready to prioritize apostrophe terms.
